name: rain_on_snow_database
channels:
 - conda-forge
 - default
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - matplotlib
 - cartopy
 - dask
 - xarray
 - h5netcdf
 - rioxarray
 - openpyxl
 - geopandas
 - aiohttp
 - pqdm
 - pytest
 - cfchecker
 - nbdime
 - pip:
     - /home/apbarret/src/nsidc_projections

 ##################################################
 # Possible dependencies to import                #
 ##################################################
 # bs4
 # fiona
 
