name: rain_on_snow_database
channels:
 - conda-forge
 - default
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - matplotlib
 - cartopy
 - dask
 - xarray
 - openpyxl
 - geopandas
 - pytest

 ##################################################
 # Possible dependencies to import                #
 ##################################################
 # bs4
 # fiona
 
