name: rain_on_snow_database
channels:
 - conda-forge
 - default
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - matplotlib
 - seaborn
 - cartopy
 - dask
 - xarray
 - h5netcdf
 - rioxarray
 - openpyxl
 - geopandas
 - aiohttp
 - pqdm
 - pytest
 - cfchecker
 - nbdime
 - geocube
 - geodatasets
 
 # For ERA5
 - cdsapi
 
 # For PGC DEM
 - pystac-client
 - ipyleaflet
 - stackstac

 # For WMTS
 - owslib
 
 - pip
 - pip:
     - /home/apbarret/src/nsidc_projections

 ##################################################
 # Possible dependencies to import                #
 ##################################################
 # bs4
 # fiona
 
